### ISSUE TITLE
Problem inserting PHP code

### ISSUE THREAD

**Issue by Benoit1980** [ranelpadon/ckeditor-prism#1]
I am finding impossible to insert this code in your plugin, it keeps cutting the bottom of the code

Here is the code
 if ($_SERVER['REQUEST_METHOD'] == "POST") { 

$errors = []; 

if(!filter_var($email, FILTER_VALIDATE_EMAIL)){ 
$errors[] = "There is an error with your email"; 
} 

if(!filter_var($url, FILTER_VALIDATE_URL)){ 
$errors[] = "There is an error with your url"; 
} 

if(!filter_var($ip, FILTER_VALIDATE_IP)){ 
$errors[] = "There is an error with your ipl"; 
} 

if(!filter_var($number, FILTER_VALIDATE_INT)){ 
$errors[] = "There is an error with xxx"; 
} 

if(!filter_var($float, FILTER_VALIDATE_FLOAT)){ 
$errors[] = "There is an error with xxx"; 
} 

if(!filter_var($boolean, FILTER_VALIDATE_BOOLEAN)){ 
$errors[] = "There is an error with xxx"; 
} 

  if($errors){
   foreach($errors as $error) {
   echo "<div class='alert alert-danger animated fadeIn' role='alert'>" . $error. "</div>";
    }
}
}

But the end keeps looking like this:

" .$error. "
"; }}}

It looks like the plugin struggles with the dots before the variables.

**Comment by ranelpadon** [comment]
I'm not really sure what you're trying to do. But, I've tried applying some tab indentations to align/organize your codes better (I've used 4 spaces = 1 tab in accordance w/ GitHub's markdown format, you could used 2 spaces = 1 tab if you want):

```
if ($_SERVER['REQUEST_METHOD'] == "POST") {
    $errors = [];

    if(!filter_var($email, FILTER_VALIDATE_EMAIL)) { 
        $errors[] = "There is an error with your email"; 
    }

    if(!filter_var($url, FILTER_VALIDATE_URL)) { 
        $errors[] = "There is an error with your url"; 
    }

    if(!filter_var($ip, FILTER_VALIDATE_IP)) { 
        $errors[] = "There is an error with your ipl"; 
    }

    if(!filter_var($number, FILTER_VALIDATE_INT)) { 
        $errors[] = "There is an error with xxx"; 
    }

    if(!filter_var($float, FILTER_VALIDATE_FLOAT)) { 
        $errors[] = "There is an error with xxx"; 
    }

    if(!filter_var($boolean, FILTER_VALIDATE_BOOLEAN)) { 
        $errors[] = "There is an error with xxx"; 
    }

    if($errors) {
        foreach($errors as $error) {
            echo " " . $error . " ";
        }
    }
}
```

Then, I injected your "formatted" code snippet in my live demo page [here](http://ranelpadon.com/sites/all/libraries/ckeditor/plugins/prism/demo/index.html), and it looks okay (see attached screenshots below). Let me know if it solved your problem or you need further help.

<img width="1288" alt="screen shot 2016-08-01 at 2 07 08 pm" src="https://cloud.githubusercontent.com/assets/4292088/17284547/3eb7348e-57ee-11e6-8935-8f821fbcc655.png">

<img width="1275" alt="screen shot 2016-08-01 at 2 06 55 pm" src="https://cloud.githubusercontent.com/assets/4292088/17284548/3eb80d96-57ee-11e6-8a61-758ff43f6742.png">

**Comment by Benoit1980** [comment]
Thank you so much for the reply.

It looks like my code did not paste properly in Github, but in the error tab, I have this:
`if($errors){
   foreach($errors as $error) {
   echo "<div class='alert alert-danger animated fadeIn' role='alert'>" . $error. "</div>";
    }`
When bootstrap 3 is installed on the website, this is what I get:
http://screencast.com/t/QcuyK0Abfi1z

It seems that the class inside the DIV is being output in the front end and not added as "code".

Thank you.

**Comment by ranelpadon** [comment]
I could replicate your issue in my local. I've activated Bootstrap also. But upon further investigation, it turned out that the root cause is the external/core Prism library itself and not the Bootstrap framework: it doesn't parse the nested markups by default (like the case for your **DIV** tag inside of the Prism's **CODE** tag). See the related Prism issue [here](https://github.com/PrismJS/prism/issues/651).

One of the quick workarounds is to replace the `<` and `>` characters by their equivalent [HTML Entities](http://www.w3schools.com/html/html_entities.asp), which are `&lt;` and `&gt;` respectively, so that it would be properly escaped.

so replace this **DIV**-containing line:
`echo "<div class='alert alert-danger animated fadeIn' role='alert'>" . $error . "</div>";`

with the properly escaped `<` and `>` characters:
`echo "&lt;div class='alert alert-danger animated fadeIn' role='alert'&gt;" . $error . "&lt;/div&gt;";`

After that, the code should render fine, both in CKEditor and in the front-end. See the screenshot below and notice the red **Alerto** text processed by Bootstrap also. 

<img width="747" alt="screen shot 2016-08-11 at 1 12 13 pm" src="https://cloud.githubusercontent.com/assets/4292088/17578988/88c212ca-5fc2-11e6-949a-d5cc49f7b39c.png">

**Comment by Benoit1980** [comment]
Thank you, yes this is what I had to do in order to bypass the problem, I wonder if the team at prism will be able to fix this.

Thanks again for your help.

**Comment by ranelpadon** [comment]
Hi @benoit1980 I'm trying to integrate the suggested solution like the one [here](http://jsfiddle.net/nauzilus/aek8udvr/1/). But upon further testing, it turned out that this line is working fine w/ out further editing/escaping:

`echo "<div class='alert alert-danger animated fadeIn' role='alert'>" . $error . "</div>";`

For example, you could try inputting that single line in the live demo page [here](http://ranelpadon.com/sites/all/libraries/ckeditor/plugins/prism/demo/index.html).
1. Try inputting that line using the **Prism** toolbar button (pop-ups a dialog window)
2. Try inputting that line using the **Source** toolbar button (shows a textarea).

In case no.1, it will work. But, in case no.2 it will not work and we'll need (HTML entities/escaping). So apparently, there's no really issue in Prism/Code Snippet plugin. It's just we're using method #2 (at least in my case before) to input the anomalous line (which is not the preferred way). So if you're using the Prism dialog window as input markup mechanism, it will work as intended since the special symbols will be auto-escaped when the user clicks the **OK** button.

Let me know if you could confirm/validate this.
